### ISSUE TITLE
How to generate manhatton plot from Scoary results

### ISSUE THREAD

**Issue by sekhwal** [AdmiralenOla/Scoary#102]
Hi,
I got the separate output .csv files of each phenotype from Scoary. Please let me know how to proceed for the visualization the results manhatton plot.

**Comment by AdmiralenOla** [comment]
Hi @sekhwal. Scoary doesn't automatically create Manhattan plots. It should be fairly simple to just extract your gene names/positions and p-values though. If you know how to use R I recommend starting with this: https://r-graph-gallery.com/101_Manhattan_plot.html
