### ISSUE TITLE
Python3 incompatibility

### ISSUE THREAD

**Issue by AdmiralenOla** [AdmiralenOla/Scoary#19]
Scoary currently doesn't work with python3. It seems to freeze and eat up memory when trying to populate the quadtree with pairwise hamming distances.

**Comment by mgalardini** [comment]
Hi,

haven't yet had the time to investigate this properly, but will give it a shot for sure.

Marco

**Comment by AdmiralenOla** [comment]
Ok, I've made it a little bit further. It seems that the main problem is that by default in python3, normal division of integers (using /) gives a float instead of an integer. This messes with the quadtree building. I'm changing the operator from / to // now. (This is also compatible with python 2.7)

**Comment by mgalardini** [comment]
Awesome!

**Comment by AdmiralenOla** [comment]
However, the script still won't run because it seems the len function doesn't work with a zip object in python3! This causes the csv_to_dic method to fail. Will have to work my way around that!

**Comment by mgalardini** [comment]
Ah, I see; let me know if I can be of any help on this

**Comment by AdmiralenOla** [comment]
Ok, fixed that by recasting some zip and dict_values objects into lists. Now checking if everything works...

**Comment by AdmiralenOla** [comment]
As far as I can tell, everything seems to be working in python3 now.
