### ISSUE TITLE
Bug found - adjusted p-value

### ISSUE THREAD

**Issue by cimendes** [AdmiralenOla/Scoary#3]
Hi

I was testing your script and i noticed that it seems to be printing the same value for the Holm-Sidak_p and Benjamini_H_p for all genes. 

Best regards

C Mendes

**Comment by AdmiralenOla** [comment]
Thank you for catching this! There appears to be some issues with regards to how Scoary adjusts p-values for multiple comparisons. I will release a bug fix later today.

**Comment by cimendes** [comment]
Hi! Thanks for the reply! I managed to fix this problem by adjusting the following lines on Scoary_methods.py (lines 200 and 201):
```
hs_corrected_p_values[gene] = (1.0-(1.0-p)**(number_of_tests - float(ind))) if gene not in tie else last_hs 
bh_corrected_p_values[gene] = p*number_of_tests/(ind+1.0) if gene not in tie else last_bh 
```
I can push my modified version to git if you do wish so. :)
