### ISSUE TITLE
SNP gwas

### ISSUE THREAD

**Issue by samlipworth** [AdmiralenOla/Scoary#65]
Hi,

I have previously got scoary to work with roary output but can't get it to work with SNP output created with the SNP2vcf.py script.

My traits file is deffinitely formatted correctly (it works with roary input)

The SNP file looks OK but I get the error:
`CRITICAL: Could not find 92dd9dbb-81ae-4faf-8867-4f27deef779f in the genes file.
CRITICAL:
Traceback (most recent call last):
  File "/home/ndm.local/sam/CSOLD/dev/lib/python2.7/site-packages/scoary/methods.py", line 278, in main
    RES_and_GTC = Setup_results(genedic, traitsdic, args.collapse)
  File "/home/ndm.local/sam/CSOLD/dev/lib/python2.7/site-packages/scoary/methods.py", line 798, in Setup_results
    stats = Perform_statistics(traitsdic[trait], genedic[gene])
  File "/home/ndm.local/sam/CSOLD/dev/lib/python2.7/site-packages/scoary/methods.py", line 979, in Perform_statistics
    sys.exit("Make sure strains are named the same in your "
SystemExit: Make sure strains are named the same in your traits file as in your gene presence/absence file
`
The vcf file definitely contains the isolate in question so I'm not sure what is going on?? Any ideas?  (the names are definitely the same too!)

**Comment by AdmiralenOla** [comment]
Thanks for submitting an issue! Not quite sure what's going on here, but the first thing I can think of is: Do you actually have an isolate named "92dd9dbb-81ae-4faf-8867-4f27deef779f" in your collection?

If you would be willing to send me some input files (or a reduced representation - just delete most of the rows) to olbb@fhi.no I could have a more thorough look at this.

**Comment by AdmiralenOla** [comment]
Closing this as it was resolved using the -s parameter.
