### ISSUE TITLE
How to output information concerning all genes ?

### ISSUE THREAD

**Issue by mylanhong** [AdmiralenOla/Scoary#70]
Hello, Ola,

After completing running, I found only genes  associated with the trait were reports. How can I get the information of all genes when using GUI  though most of them were not significant ?

 Kind regards, 

Lanhong

**Comment by AdmiralenOla** [comment]
Hi @mylanhong.

Just remove the checks in all cut-off boxes. This means every gene will be reported, regardless of association.

Side note: I really recommend you to use the command line instead of the GUI. It will be a lot faster and less buggy.

Best regards,
Ola
