### ISSUE TITLE
Segentation fault

### ISSUE THREAD

**Issue by giggzie02** [AdmiralenOla/Scoary#71]
I am trying to run Scoary on dataset of 26 strains and 6927 genes. The program begins executing until a point where it is killed and returns a segmentation error. Does this mean I do not have sufficient memory to run the analysis?

**Comment by AdmiralenOla** [comment]
Hi @giggzie02. It's not possible to say what the problem is since a lot of different errors can throw a segmentation fault. You could try e-mailing me your files (input files, a log file from a run that didn't work, and your scoary version) at olbb@fhi.no, and I'll have a look.
