### ISSUE TITLE
Piggy output as input to use with Scoary?

### ISSUE THREAD

**Issue by maesaar** [AdmiralenOla/Scoary#78]
Is it possible to use [piggy](https://github.com/harry-thorpe/piggy) output (IGR_presence_absence.csv) as input for Scoary?

**Comment by Antonia-Chalka** [comment]
this is probably too late for your case, but for reference's sake, you can use piggy's IGR_presence_absence as input just fine!

**Comment by maesaar** [comment]
Thank you!

**Comment by AdmiralenOla** [comment]
Thank you @Antonia-Chalka! Covid stole my extra time!
