### ISSUE TITLE
Splitting paralogs influence to Scoary?

### ISSUE THREAD

**Issue by nbawe** [AdmiralenOla/Scoary#79]
@AdmiralenOla does not splitting paralogs (-s in roary) affect Scoary results?

**Comment by AdmiralenOla** [comment]
Hi, @nbawe. Scoary actually doesn't care what parameters you used in Roary at all. It simply accepts the input files as "the truth".

If Roary split paralogs into multiple genes in your gene presence/absence file, then Scoary will never know that these genes are paralogs. It will treat them as two distinct units.

On a related note, I know some people have problems with Roary being overly enthusiastic about splitting genes that from an evolutionary point of view are the same. If you have problems with this I suggest using the pan-genome program Panaroo instead. It is less prone to split genes that have identical genomic neighborhood for example. It is available at Gerry Tonkin-Hill's github: https://github.com/gtonkinhill/panaroo

**Comment by AdmiralenOla** [comment]
Since it is not really an issue I'll be closing this
