### ISSUE TITLE
Self created absence_presence file as input?

### ISSUE THREAD

**Issue by maesaar** [AdmiralenOla/Scoary#85]
Is it possible to use self created absence_presence data file? For example for virulence genes detected with abricate?

**Comment by AdmiralenOla** [comment]
Hi @mmaesaar - That is absolutely possible. Your input file has to follow the Roary gene presence/absence structure vaguely, eg the columns need to correspond to presence/absence in your input and the rows to your various genes/variants.

I strongly recommend that you reserve the first three columns in your input file for gene/variant annotation, as examplified in Roary's "Gene", "Non-unique Gene name" and "Annotation". You can have your presence/absence data starting at column 4. Make sure to alter the --start_col parameter parameter if you do this.

**Comment by maesaar** [comment]
Thank you @AdmiralenOla
