### ISSUE TITLE
Separate trait files

### ISSUE THREAD

**Issue by zakisaati** [AdmiralenOla/Scoary#87]
Hi!

I was having RAM problems to run scoary. I was able to solve it by using a traits.csv file per trait instead of using a single traits.csv file with all the different traits. However, I am not sure if this is going to modify the statistic calculations. My purpose is to find bacterial proteins associated to the isolation source of the bacteria, so I am doing a similar approach to that explained with "cattle, human, sheep and food" in the main page of Scoary in github ("Enrichment of genes in select host groups"). So, the question is:
Can I use a single csv file per trait and run the process different times instead of a unique csv file with all the traits?

Thank you very much in advance

**Comment by AdmiralenOla** [comment]
Hi @zakisaati,

Yes, you can spread your traits across multiple input files. This does not impact the results.
